Vagrant.configure("2") do |config|

    config.vm.box = "centos/7"
    config.vm.hostname = "abenaniS"
    config.vm.provider "virtualbox" do |vb|
        vb.name = "abenaniS"
        vb.memory = 3072
    end
    config.vm.network "private_network", ip: "192.168.42.110"
    config.vm.provision "shell", privileged: false, path: "./setup.sh"
end