Vagrant.configure("2") do |config|

    config.vm.box = "centos/7"
    config.vm.hostname = "abenaniS"
    config.vm.provider "virtualbox" do |vb|
        vb.name = "abenaniS"
        vb.memory = 1024
    end
    config.vm.network "private_network", ip: "192.168.42.110"
    config.vm.provision "shell", inline: <<-SHELL
    curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" sh -s - \
    kubectl apply -f /vagrant/app-one.yaml \
    kubectl apply -f /vagrant/service-one.yaml
    SHELL
end