Vagrant.configure("2") do |config|

    config.vm.box = "centos/7"
    
    config.vm.define "server" do |server|
        server.vm.hostname = "abenaniS"
        server.vm.network "private_network", ip: "192.168.42.110"
        server.vm.provider "virtualbox" do |vb|
            vb.name = "abenaniS"
            vb.memory = 1024
            vb.cpus = 1
        end
        server.vm.provision "shell", privileged: true, inline: <<-SHELL
        curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE=644 sh -
        # vagrant scp /var/lib/rancher/k3s/server/node-token .
        SHELL
    end

    # config.vm.define "worker" do |worker|
    #     worker.vm.hostname = "abenaniSW"
    #     worker.vm.network "private_network", ip: "192.168.42.111"
    #     worker.vm.provider "virtualbox" do |vb|
    #         vb.name = "abenaniSW"
    #         vb.memory = 1024
    #         vb.cpus = 1
    #     end
    #     worker.vm.provision "shell", privileged: true, inline: <<-SHELL
    #     curl -sfL https://get.k3s.io | K3S_TOKEN=????? K3S_URL=https://192.168.42.110:6443 K3S_KUBECONFIG_MODE=644 sh -
    #     SHELL
    # end
    
end