Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"

    config.vm.define "abenaniS" do |server|
        server.vm.hostname = "abenaniS"
        server.vm.network "private_network", ip: "192.168.42.110"
        server.vm.provider "virtualbox" do |v|
            v.name = "abenaniS"
            v.memory = 1024
            v.cpus = 1
        end
        server.vm.provision "shell", inline: <<-SHELL
        curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="--flannel-iface eth1" sh -s -
        echo $(sudo cat /var/lib/rancher/k3s/server/node-token) > /vagrant/.token
        SHELL
        server.trigger.after :up do |trigger|
            trigger.run = {inline: "vagrant scp abenaniS:/vagrant/.token ."}
        end
    end

    config.vm.define "abenaniSW" do |worker|
        worker.vm.hostname = "abenaniSW"
        worker.vm.network "private_network", ip: "192.168.42.111"
        worker.vm.provider "virtualbox" do |v|
            v.name = "abenaniSW"
            v.memory = 1024
            v.cpus = 1
        end
        worker.vm.provision "shell", inline: <<-SHELL
        curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" K3S_URL=https://192.168.42.110:6443 K3S_TOKEN=$(cat /vagrant/.token) INSTALL_K3S_EXEC="--flannel-iface eth1" sh -s -
        SHELL
        worker.trigger.after :up do |trigger|
            trigger.run = {inline: "rm .token"}
        end
    end
    
end