Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.hostname = "abenani"
    config.vm.provider "virtualbox" do |vb|
        vb.name = "abenani"
        vb.memory = 3072
    end
    config.vm.network "private_network", ip: "192.168.42.110"
    # config.vm.provision "shell", path: "./scripts/setup.sh"
end