Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.hostname = "gitlab"
    config.vm.provider "virtualbox" do |vb|
        vb.name = "gitlab"
        vb.memory = 512
        vb.cpus = 1
    end
    config.vm.network "private_network", ip: "192.168.42.100"
    config.vm.provision "shell", privileged: false, path: "./scripts/setup.sh"
end
